[package]
name = "plans"
description = "Time-locked bill payment vault for financial discipline"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[package.metadata.stellar]
cargo_inherit = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
stellar-xdr = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
